// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smvyylcbhfkfplxxpqou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtdnl5bGNiaGZrZnBseHhwcW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMjU4ODQsImV4cCI6MjA1NzcwMTg4NH0.H8bSXSiY6Tpl01RbJWF5OjgRl5maCJ1nlP3qH0KxErk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);